name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          DEPLOY_SERVER: "indigofur.com"  # Your cPanel domain
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        env:
          DEPLOY_SERVER: "indigofur.com"  # Ensure this matches the previous step
          DEPLOY_PATH: "public_html/test.indigofur.com.au"  # Deployment folder on cPanel
          USERNAME: " "  # Replace with your cPanel username
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" . ${USERNAME}@${DEPLOY_SERVER}:${DEPLOY_PATH}
