name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Replace "main" with your branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        env:
          DEPLOY_SERVER: "test.indigofur.com.au"  # Your cPanel domain
          DEPLOY_PATH: "/public_html/test.indigofur.com.au"  # Correct deployment folder path
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
          
          # Use rsync to deploy the repository to the empty directory on the server
          rsync -avz --delete --exclude='.git' . l405v2pekias@${DEPLOY_SERVER}:${DEPLOY_PATH}
